<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Employee_Checkbox_1</name>
   <tag></tag>
   <elementGuidId>a5bcdcba-aba3-44ec-afab-ec39275e9529</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>((//input[@type='checkbox'])[2]/following::span/i)[1]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
